### ISSUE TITLE
T2_Realidad Aumentada en sitio web

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/actividad-5-realidad-aumentada-en-sitio-web-team-vo#1]
[RA_T2_Web.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-realidad-aumentada-en-sitio-web-team-vo/files/14949867/RA_T2_Web.pdf)

**Comment by MLR062998** [comment]
18

**Comment by josealfredo79** [comment]
bien hecho y revisado...
